### ISSUE TITLE
jQuery replacement

### ISSUE THREAD

**Issue by piotrfilipek** [daviddarnes/awetheme#1]
Seriously? You are using jQuery to animate footer ([in 13-19 lines](https://github.com/daviddarnes/awetheme/blob/master/header.php#L13-19))? It can be done by using only CSS:

``` css
footer {
    opacity: 0.5;
    transition: ease-in-out 0.1s;
}

footer:hover {
    opacity: 1;
}
```
